export const projects = [
  {
    id: 1,
    image: '/images/projects/nostra.webp',
    techImage: '/images/technologies/nextjs.svg',
    title: 'Nostra-Pizza',
    description:
      "A full-stack application for food ordering with Google authentication and order confirmations via email. Users can browse products, with some offering additional options like extra portions of meat. Orders are placed through a form that includes a phone number input mask and a Google address input for delivery. Regular users can view their order history, while admins have access to a dedicated panel. Orders are sent to the owner's Gmail. MongoDB stores all products and orders from authenticated users. The app is responsive, supports various devices, and allows users to save products to their favorites.",
    techstack:
      'Next.js, TypeScript, Redux-Toolkit, React Hook Form, MongoDB, Google Maps, OAuth, Vercel',
    role: 'Full-Stack Developer & Product Creator',
    liveUrl: 'https://nostrra-pizzza.vercel.app',
    githubUrl: 'https://github.com/Yevhenns/pizza-app-router.git',
  },
  {
    id: 2,
    image: '/images/projects/evently.webp',
    techImage: '/images/technologies/react.svg',
    title: 'Book my event',
    description:
      'I integrated RTK Query with optimistic updates for likes, enabling a smoother user experience. I also implemented the Google Maps API and performed unit testing to ensure robust functionality. On the /all_events page, I developed advanced filters, improving event search and categorization. I created a form for the /user_profile page, enhancing user profile management. In addition, I resolved multiple bugs, ensuring the application runs seamlessly. I addressed design inconsistencies, aligning the implementation with Figma prototypes to improve visual consistency. I also provided ongoing support to other developers, assisting with technical challenges and code review.',
    techstack: 'React, TypeScript, Redux-Toolkit, RTK-Query, Vitest, Figma, Jira',
    role: 'Front-End Developer',
    liveUrl: 'https://evently-book.vercel.app',
    githubUrl: 'https://github.com/McLareni/evently_front.git',
  },
  {
    id: 3,
    image: '/images/projects/nostra-mobile.webp',
    techImage: '/images/technologies/react.svg',
    title: 'Nostra-Pizza',
    description: 'Mobile application for Nostra Pizza',
    techstack: 'React-Native, TypeScript, Redux-Toolkit, React Hook Form, Google Maps, OAuth',
    role: 'Front-End Developer & Product Creator',
    liveUrl: null,
    githubUrl: 'https://github.com/Yevhenns/pizza_mob.git',
  },
  {
    id: 4,
    image: '/images/projects/novaposhta.webp',
    techImage: '/images/technologies/vue.svg',
    title: 'Novaposhta tracker',
    description: 'Google Chrome extension for tracking parcels',
    techstack: 'Vue3, TypeScript, Pinia, Vue-Router, Vercel',
    role: 'Front-End Developer & Product Creator',
    liveUrl: 'https://np-extension.vercel.app/',
    githubUrl: 'https://github.com/Yevhenns/np-extension.git',
  },
  {
    id: 5,
    image: '/images/projects/nostra-back.webp',
    techImage: '/images/technologies/nestjs.svg',
    title: 'Nostra Pizza',
    description: 'Back-End application for Nostra Pizza',
    techstack: 'Nest.js, TypeScript, MongoDB, Swagger, Render',
    role: 'Back-End Developer & Product Creator',
    liveUrl: 'https://pizza-nest.onrender.com/api',
    githubUrl: 'https://github.com/Yevhenns/pizza-nest.git',
  },
]
