export const projects = [
  {
    id: 1,
    image: '/images/projects/nostra.webp',
    techImage: '/images/technologies/nextjs.svg',
    title: 'Nostra-Pizza',
    description:
      'Full-stack application with Google authentication for ordering food and receiving order confirmations via email. Users can view their order history. Developed in collaboration with a UI/UX designer',
    techstack:
      'Next.js, TypeScript, Redux-Toolkit, React Hook Form, MongoDB, Google Maps, OAuth, Vercel',
    role: 'Full-Stack Developer & Product Creator',
    liveUrl: 'https://nostrra-pizzza.vercel.app',
    githubUrl: 'https://github.com/Yevhenns/pizza-app-router.git',
  },
  {
    id: 2,
    image: '/images/projects/evently.webp',
    techImage: '/images/technologies/react.svg',
    title: 'Book my event',
    description:
      'I integrated unit testing, RTK Query with optimistic updates for likes and Google Maps Api. I developed advanced filters for the /all_events page, a form for the /user_profile page and resolved multiple bugs. Additionally, I addressed design inconsistencies, aligning the implementation with Figma prototypes. I also assist other developers on the project',
    techstack: 'React, TypeScript, Redux-Toolkit, RTK-Query, Vitest, Figma, Jira',
    role: 'Front-End Developer',
    liveUrl: 'https://evently-book.vercel.app',
    githubUrl: 'https://github.com/McLareni/evently_front.git',
  },
  {
    id: 3,
    image: '/images/projects/nostra-mobile.webp',
    techImage: '/images/technologies/react.svg',
    title: 'Nostra-Pizza',
    description: 'Mobile application for Nostra Pizza',
    techstack: 'React-Native, TypeScript, Redux-Toolkit, React Hook Form, Google Maps, OAuth',
    role: 'Front-End Developer & Product Creator',
    liveUrl: null,
    githubUrl: 'https://github.com/Yevhenns/pizza_mob.git',
  },
  {
    id: 4,
    image: '/images/projects/novaposhta.webp',
    techImage: '/images/technologies/vue.svg',
    title: 'Novaposhta tracker',
    description: 'Google Chrome extension for tracking parcels',
    techstack: 'Vue3, TypeScript, Pinia, Vue-Router, Vercel',
    role: 'Front-End Developer & Product Creator',
    liveUrl: 'https://np-extension.vercel.app/',
    githubUrl: 'https://github.com/Yevhenns/np-extension.git',
  },
  {
    id: 5,
    image: '/images/projects/nostra-back.webp',
    techImage: '/images/technologies/nestjs.svg',
    title: 'Nostra Pizza',
    description: 'Back-End application for Nostra Pizza',
    techstack: 'Nest.js, TypeScript, MongoDB, Swagger, Render',
    role: 'Back-End Developer & Product Creator',
    liveUrl: 'https://pizza-nest.onrender.com/api',
    githubUrl: 'https://github.com/Yevhenns/pizza-nest.git',
  },
]
