export const projects = [
  {
    id: 1,
    image: '/public/projects/nostra.jpg',
    title: 'Nostra-Pizza',
    description:
      'Full-stack application with Google authentication for ordering food and receiving order confirmations via email. Users can view their order history. Developed in collaboration with a UI/UX designer.',
    techstack: 'Next.js, TypeScript, Redux-Toolkit, React Hook Form, Google Maps, OAuth, Vercel.',
    role: 'Full-Stack Developer & Product Creator',
    liveUrl: 'https://nostrra-pizzza.vercel.app',
    githubUrl: 'https://github.com/Yevhenns/pizza-app-router.git',
  },
  {
    id: 2,
    image: '/public/projects/nostra-back.jpg',
    title: 'Nostra Pizza',
    description: 'Back-End application for Nostra Pizza.',
    techstack: 'Nest.js, TypeScript, MongoDB, Swagger, Render.',
    role: 'Back-End Developer & Product Creator',
    liveUrl: 'https://pizza-nest.onrender.com/api',
    githubUrl: 'https://github.com/Yevhenns/pizza-nest.git',
  },
  {
    id: 3,
    image: '/public/projects/nostra-mobile.jpg',
    title: 'Nostra-Pizza',
    description: 'Mobile application for Nostra Pizza.',
    techstack: 'React-Native, TypeScript, Redux-Toolkit, React Hook Form, Google Maps, OAuth.',
    role: 'Front-End Developer & Product Creator',
    liveUrl: null,
    githubUrl: 'https://github.com/Yevhenns/pizza_mob.git',
  },
  {
    id: 4,
    image: '/public/projects/novaposhta.jpg',
    title: 'Novaposhta tracker',
    description: 'Google Chrome extension for tracking parcels.',
    techstack: 'Vue3, TypeScript, Pinia, Vue-Router, Vercel.',
    role: 'Front-End Developer & Product Creator',
    liveUrl: 'https://np-extension.vercel.app/',
    githubUrl: 'https://github.com/Yevhenns/np-extension.git',
  },
]
